# Generated by Django 4.2.19 on 2025-05-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_date", models.DateField()),
                (
                    "reservation_time",
                    models.CharField(
                        choices=[
                            ("11:00", "11:00"),
                            ("11:30", "11:30"),
                            ("12:00", "12:00"),
                            ("12:30", "12:30"),
                            ("13:00", "13:00"),
                            ("13:30", "13:30"),
                            ("14:00", "14:00"),
                            ("14:30", "14:30"),
                            ("15:00", "15:00"),
                            ("15:30", "15:30"),
                            ("16:00", "16:00"),
                            ("16:30", "16:30"),
                            ("17:00", "17:00"),
                            ("17:30", "17:30"),
                            ("18:00", "18:00"),
                            ("18:30", "18:30"),
                            ("19:00", "19:00"),
                            ("19:30", "19:30"),
                            ("20:00", "20:00"),
                        ],
                        default="11:00",
                        max_length=5,
                    ),
                ),
                ("no_of_guests", models.PositiveSmallIntegerField(default=1)),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("Birthday", "Birthday"),
                            ("Anniversary", "Anniversary"),
                            ("Other", "Other"),
                        ],
                        default="Birthday",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "menu_item_description",
                    models.TextField(default="", max_length=1000),
                ),
                ("inventory", models.IntegerField()),
            ],
        ),
    ]
