# Generated by Django 4.2.19 on 2025-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="inventory",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
