# Generated by Django 4.2.21 on 2025-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurante",
            "0002_cart_category_menuitem_order_orderitem_delete_menu_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
