# Generated by Django 4.2.21 on 2025-05-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurante", "0003_menuitem_description_menuitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField(default=restaurante.models.hundred_years_ago)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("B", "Bisexual"),
                            ("T", "Transgender"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="Hajipur", max_length=100),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="Bihar", max_length=100),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Married"),
                            ("U", "Unmarried"),
                            ("N", "Not Applicable"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LL", "Likh Lodha Padh Patthar"),
                            ("BH", "Below High School"),
                            ("HS", "High School"),
                            ("BS", "Bachelor’s Degree"),
                            ("GD", "Graduate Degree"),
                        ],
                        default="LL",
                        max_length=2,
                    ),
                ),
                (
                    "income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B", "Bhikhari"),
                            ("L", "Below $100K"),
                            ("M", "$100K-$200K"),
                            ("H", "Above $200K"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
