# Generated by Django 4.2.21 on 2025-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
