# Generated by Django 4.2.21 on 2025-06-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0005_booking_email"),
    ]

    operations = []
