# Generated by Django 4.2.21 on 2025-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0006_backfill_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True
            ),
        ),
    ]
