# Generated by Django 4.2.21 on 2025-06-01 13:21

from django.db import migrations
import uuid

def backfill_reference_numbers(apps, schema_editor):
    Booking = apps.get_model('restaurante', 'Booking')
    for booking in Booking.objects.all():
        if not booking.reference_number:
            booking.reference_number = uuid.uuid4().hex[:12].upper()
            booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0008_backfill_reference_number"),
    ]

    operations = [
        migrations.RunPython(backfill_reference_numbers),
    ]
