# Generated by Django 4.2.21 on 2025-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0009_backfill_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_pin",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_slot",
            field=models.CharField(default="ASAP", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                default="delivery",
                max_length=10,
            ),
        ),
    ]
