# Generated by Django 4.2.21 on 2025-06-07 02:59

from django.db import migrations, models
import restaurante.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0011_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(db_index=True, default=restaurante.models.today),
        ),
    ]
