# Generated by Django 4.2.21 on 2025-06-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0014_customerreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
