# Generated by Django 4.2.23 on 2025-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0016_booking_user_alter_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("cod", "Cash on Delivery")],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
