# Generated by Django 4.2.23 on 2025-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0018_chathistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="function_arguments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="function_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="function_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("function", "Function"),
                ],
                max_length=20,
            ),
        ),
    ]
