# Generated by Django 4.2.23 on 2025-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0019_chathistory_function_arguments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
